#!/bin/sh

if test $# -eq 0
then
	echo "usage $0 wireshark-source-directory" 2>&1
	exit 1
fi

TOT=$1
here=$(/bin/pwd)

if [ ! -f $TOT/WiresharkConfig.cmake.in ]
then

	echo "$TOT/WiresharkConfig.cmake.in not found" 2>&1
	echo "usage $0 wireshark-source-directory" 2>&1
	exit 1
fi

set -x

cd $TOT
mkdir -p build
cd build
cmake -G "Unix Makefiles" \
  -DDISABLE_WERROR=ON \
  -DBUILD_wireshark=ON \
  -DENABLE_LUA=ON \
  -DBUILD_mmdbresolve=OFF \
  -DBUILD_randpktdump=OFF \
  -DBUILD_androiddump=ON \
  -DENABLE_SMI=ON \
  -DUSE_qt6=ON \
  -DENABLE_PLUGINS=ON \
  -DENABLE_NETLINK=ON \
  -DBUILD_dcerpcidl2wrs=OFF \
  -DBUILD_sdjournal=ON \
  ..  || exit 1
  

make
